#!/usr/bin/env python3
"""
Repo status dashboard — one screen: open decisions, open defects, recent
commits, and uncommitted changes. Generated by the repo-harness-init skill.

Run: python scripts/status.py   (or: make status, if the project wires that up)

This is deliberately dependency-free (standard library only) so it keeps
working even if the project's own environment is broken — status should be
checkable even when nothing else is.
"""
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def run_git(args):
    try:
        result = subprocess.run(
            ["git"] + args, cwd=ROOT, capture_output=True, text=True, check=False
        )
        return result.stdout.strip()
    except FileNotFoundError:
        return ""


def open_items(dir_name, resolved_marker="resolved"):
    d = ROOT / dir_name
    if not d.exists():
        return None  # directory doesn't exist -> not set up, vs. [] -> set up and empty
    items = []
    for f in sorted(d.glob("*.md")):
        text = f.read_text(errors="ignore").lower()
        if resolved_marker not in text:
            items.append(f.relative_to(ROOT))
    return items


def section(title):
    print(f"\n{title}")
    print("-" * len(title))


def print_list(items, empty_msg):
    if not items:
        print(f"  {empty_msg}")
        return
    for item in items:
        print(f"  - {item}")


def main():
    print("=" * 60)
    print("REPO STATUS")
    print("=" * 60)

    section("Open defects / safety items")
    defects = (open_items("docs/status-defects") or []) + (open_items("docs/safety") or [])
    print_list(defects, "(none open)")

    section("Recent decisions")
    decisions = ROOT / "docs" / "decisions"
    if decisions.exists():
        recent = sorted(decisions.glob("*.md"))[-5:]
        print_list(recent, "(none yet)")
    else:
        print("  (docs/decisions/ not set up)")

    section("Recent commits")
    log = run_git(["log", "-5", "--oneline"])
    print(f"  {log}" if log else "  (no git history)")

    section("Uncommitted changes")
    status = run_git(["status", "--short"])
    print(status if status else "  (clean)")

    print()


if __name__ == "__main__":
    main()
